before_script:
    #pre-installation script
    - cd ..
    - shopt -s extglob
    - rm -rf !(ILCDIRAC)
    - rm -rf .installCache
    - mv ILCDIRAC ILCDIRAC_commit
    - wget -O dirac-install -np  https://raw.github.com/DIRACGrid/DIRAC/master/Core/scripts/dirac-install.py  --no-check-certificate
    - chmod +x dirac-install
    - ./dirac-install -V ILCDIRAC -r v25r0p0
    - rm -rf DIRAC
    - mkdir DIRAC
    - cd DIRAC
    - git clone https://github.com/DIRACGrid/DIRAC.git .
    - git checkout origin/rel-v6r14
    - cd ..
    - rm -rf ILCDIRAC
    - mv ILCDIRAC_commit ILCDIRAC
    - source bashrc
    - dirac-deploy-scripts
    - pip install --upgrade --force-reinstall pip
    - pip install --upgrade --force-reinstall pylint
    - pip install --upgrade --force-reinstall nose
    - pip install --upgrade --force-reinstall mock
    - pip install --upgrade --force-reinstall coverage
    - pip install --upgrade --force-reinstall MySQL-python
    - cd ILCDIRAC
    - dirac-proxy-init -x
#   - dirac-configure -S ILC-Production -C dips://voilcdirac01.cern.ch:9135/Configuration/Server --SkipCAChecks




pylint5:
  tags:
    - docker
  image: ilcdirac/slc5-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

nosetest5:
  tags:
    - docker
  image: ilcdirac/slc5-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-nosetests.sh

cvmfstests5:
  tags:
    - docker
  image: ilcdirac/slc5-base
  script:
    - source ../bashrc
    - python .gitlab-ci.d/run-cvmfstests.py



pylint6:
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

nosetest6:
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-nosetests.sh

cvmfstests6:
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - python .gitlab-ci.d/run-cvmfstests.py




pylint7:
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

nosetest7:
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-nosetests.sh

cvmfstests7:
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - python .gitlab-ci.d/run-cvmfstests.py
