before_script:
  - echo $LCG_BUNDLE_VERSION $ILCDIRAC_VERSION $DIRAC_BRANCH $SETUP
  - source /cvmfs/clicdp.cern.ch/software/git/2.13.2/x86_64-slc6-gcc7-opt/setup.sh
  - shopt -s extglob

stages:
  - install
  - unittest
  - manualdeploy
  - integration
  - create
  - deploy
  - deployToCVMFS

variables:
  LCG_BUNDLE_VERSION: "v14r2"
  ILCDIRAC_VERSION: "v29r0-pre1"
  DIRAC_BRANCH: "rel-v6r20"
  DIRAC_TAG: "v6r20p7"
  SETUP: "ILC-Production"
  ILCDIRAC_BRANCH: "Rel-v29r0"

.install_template: &install
  stage: install
  script:
    - cd ../
    - rm -rf !(ILCDIRAC) .installCache
    - mv ILCDIRAC ILCDIRAC_commit
    - mkdir ILCDIRAC; cd ILCDIRAC
    - mkdir installation; cd installation
    - wget -O dirac-install -np  https://raw.github.com/DIRACGrid/DIRAC/master/Core/scripts/dirac-install.py  --no-check-certificate
    - chmod +x dirac-install
    - ./dirac-install -V ILCDIRAC -r $ILCDIRAC_VERSION -g $LCG_BUNDLE_VERSION
    - rm -rf DIRAC
    - git clone https://github.com/DIRACGrid/DIRAC.git --single-branch -b $DIRAC_BRANCH DIRAC
    - rm -rf ILCDIRAC
    - mv ../../ILCDIRAC_commit ILCDIRAC
    - rm -rf .installCache
    - source bashrc
    - dirac-deploy-scripts
    - unset REQUESTS_CA_BUNDLE
    - pip install --upgrade pip
    - pip uninstall -y distribute
    - pip install --upgrade setuptools || echo "done"
    - pip install --upgrade setuptools_scm || echo "done scm"
    - pip install --upgrade pylint mock MySQL-python pytest-cov pytest-randomly pytest-mock flake8 psutil flake8-docstrings flake8-commas
    - cd ..
  artifacts:
     paths:
       - installation
     expire_in: 2 hours
  retry: 2

.sl6docker_template: &sl6docker
  tags:
    - docker
  image: gitlab-registry.cern.ch/clicdp/ilcdirac/ilcdirac-ci-images:slc6

.cc7docker_template: &cc7docker
  tags:
    - docker
  image: gitlab-registry.cern.ch/clicdp/ilcdirac/ilcdirac-ci-images:cc7

install:SL6:
  <<: *install
  <<: *sl6docker


install:CC7:
  <<: *install
  <<: *cc7docker
  except:
    - tags

codequality:
  stage: integration
  except:
    - tags
  tags:
    - overlay
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]
  allow_failure: true
  before_script: []
  after_script: []
  dependencies: []


.unittest_template: &unittest
  stage: unittest
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - source ../bashrc
    - unset PYTHONOPTIMIZE
    - .gitlab-ci.d/run-unittests.sh
  coverage: '/\d+\%\s*$/'
  artifacts:
     paths:
       - installation/ILCDIRAC/.coverage
       - installation/ILCDIRAC/htmlcov
     expire_in: 2 hours
  retry: 2
  except:
    - tags

unittest:SL6:
  <<: *unittest
  <<: *sl6docker
  dependencies:
    - install:SL6

unittest:CC7:
  <<: *unittest
  <<: *cc7docker
  dependencies:
    - install:CC7


checkFormat:
  <<: *sl6docker
  allow_failure: true
  retry: 2
  stage: unittest
  dependencies:
    - install:SL6
  except:
    - tags
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - source ../bashrc
    - git remote add CLICDP https://gitlab.cern.ch/CLICdp/iLCDirac/ILCDIRAC.git
    - git fetch --no-tags CLICDP ${ILCDIRAC_BRANCH}:${ILCDIRAC_BRANCH}
    - git diff -U0 $(git merge-base HEAD CLICDP/$ILCDIRAC_BRANCH) | flake8 --diff
    - echo "Formatting correct"


.pylint_template: &pylint
  stage: integration
  except:
    - tags
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - source ../bashrc
    - unset PYTHONOPTIMIZE
    - .gitlab-ci.d/run-pylint.sh
  retry: 2

pylint:SL6:
  <<: *sl6docker
  <<: *pylint
  dependencies:
   - install:SL6

pylint:CC7:
  <<: *cc7docker
  <<: *pylint
  dependencies:
    - install:CC7


.jobTests_template: &jobTests
  stage: integration
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - source ../bashrc
    - dirac-proxy-init --rfc -x <<< $CERT_PASSPHRASE
    - dirac-configure -S $SETUP -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - echo "mysql:x:0:0:MySQL Server:/var/lib/mysql:/bin/bash" >> /etc/passwd
    - unset PYTHONOPTIMIZE
    - .gitlab-ci.d/run-cvmfstests.sh
  coverage: '/\d+\%\s*$/'
  retry: 2
  artifacts:
    paths:
      - installation/ILCDIRAC/tmp*/Local_*/*Step*.log
    when: on_failure
    expire_in: 2 days

.prodOnly: &prod
  only:
    - branches@CLICdp/iLCDirac/ILCDIRAC
  except:
    - tags
  allow_failure: false

.devsOnly: &devs
  except:
    - tags
    - branches@CLICdp/iLCDirac/ILCDIRAC
  allow_failure: true

.sl6int: &sl6integration
  <<: *sl6docker
  dependencies:
    - install:SL6
    - unittest:SL6

.cc7: &cc7integration
  <<: *cc7docker
  dependencies:
    - install:CC7
    - unittest:CC7

jobTests:SL6:
  <<: *jobTests
  <<: *devs
  <<: *sl6integration

jobTests:SL6Prod:
  <<: *jobTests
  <<: *prod
  <<: *sl6integration

jobTests:CC7:
  <<: *jobTests
  <<: *devs
  <<: *cc7integration

jobTests:CC7Prod:
  <<: *jobTests
  <<: *prod
  <<: *cc7integration

.seTests_template: &seTests
  stage: integration
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - source ../bashrc
    - dirac-proxy-init --rfc -x <<< $CERT_PASSPHRASE
    - dirac-configure -S $SETUP -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - dirac-proxy-init --rfc <<< $CERT_PASSPHRASE
    - .gitlab-ci.d/run-setests.sh
  coverage: '/\d+\%\s*$/'
  retry: 2
  only:
    - schedules

setests:SL6:
  <<: *seTests
  <<: *devs
  <<: *sl6integration

setests:SL6Prod:
  <<: *seTests
  <<: *prod
  <<: *sl6integration

setests:CC7:
  <<: *seTests
  <<: *devs
  <<: *cc7integration

setests:CC7Prod:
  <<: *seTests
  <<: *prod
  <<: *cc7integration

compiledoc:
  <<: *sl6docker
  stage: unittest
  dependencies:
    - install:SL6
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - source ../bashrc
    - unset REQUESTS_CA_BUNDLE
    - pip install sphinx==1.7.5
    - rm -rf ILCDIRAC ## removes just the folder with the links
    - wget -O release.notes https://gitlab.cern.ch/CLICdp/iLCDirac/ILCDIRAC/raw/master/release.notes ## get release notes from the master
    - cd docs
    - export PYTHONPATH=$PWD/source:$PYTHONPATH
    - bash patchSphinx.sh
    - SPHINXOPTS=-wsphinxWarnings make completeDocumentation
    - mv build/html ../../../ilcdiracdoc
    - if [ -s sphinxWarnings ]; then cat sphinxWarnings; echo "Warnings When Creating Doc"; exit 1; fi
  artifacts:
    paths:
      - ilcdiracdoc
    expire_in: 2 hours
    when: always
  allow_failure: true
  retry: 2

maketarballs:
  <<: *sl6docker
  stage: create
  only:
    - tags@CLICdp/iLCDirac/ILCDIRAC
  dependencies:
    - install:SL6
  script:
    - export HOME=/root/
    - cd installation/ILCDIRAC
    - if [ -d "ILCDIRAC" ]; then echo "ILCDIRAC links still present! Failing!"; exit 1; fi
    - source ../bashrc
    - dirac-proxy-init --rfc -x <<< $CERT_PASSPHRASE
    - dirac-configure -S $SETUP -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - dirac-proxy-init --rfc <<< $CERT_PASSPHRASE
    - echo -e "DefaultModules = ILCDIRAC\n\nSources\n{\n  ILCDIRAC = https://gitlab.cern.ch/CLICdp/iLCDirac/ILCDIRAC.git\n}\nReleases\n{\n $CI_COMMIT_TAG\n  {\n    Modules = ILCDIRAC:$CI_COMMIT_TAG\n    Depends = DIRAC:$DIRAC_TAG\n  }\n}\n" > thisrelease.cfg
    - cat thisrelease.cfg
    - dirac-distribution -l ILCDIRAC -r $CI_COMMIT_TAG -D ../../ILCDIRACTars -C thisrelease.cfg
  artifacts:
    paths:
      - ILCDIRACTars
    expire_in: 2 hours
  retry: 2


makeILCConfig:
  <<: *sl6docker
  stage: create
  only:
    - tags@CLICdp/iLCDirac/ILCDIRAC
  except:
    - /.*-pre[0-9]*/
  dependencies:
    - install:SL6
  script:
    - mkdir -p ILCDIRACTars/defaults;  echo -e "Releases = https://gitlab.cern.ch/CLICdp/iLCDirac/ILCDIRAC/raw/master/releases.cfg\nUploadCommand = ( cd %OUTLOCATION% ; tar -cf - *.tar.gz *.md5 *.cfg *.pdf *.html ) | ssh \`whoami\`@lxplus.cern.ch \'cd  /eos/project/l/lcd-web/www/ILCDIRACTars &&  tar -xvf - && ls *.tar.gz > tars.list\'\nBaseURL = http://lcd-data.web.cern.ch/lcd-data/ILCDIRACTars\nLocalInstallation\n{\n  Project = ILCDIRAC\n  ExternalsType = client\n  PythonVersion = 27\n  Release = $CI_COMMIT_TAG\n  LcgVer = $LCG_BUNDLE_VERSION\n  Setup = ILC-Production\n  ConfigurationServer = dips://voilcdirac01.cern.ch:9135/Configuration/Server, dips://voilcdirac012.cern.ch:9135/Configuration/Server\n}\n" > ILCDIRACTars/defaults/ilc.cfg
  artifacts:
    paths:
      - ILCDIRACTars
    expire_in: 2 hours
  retry: 2


deploydoc:
  stage: deploy
  tags:
    - docker
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  only:
    - tags@CLICdp/iLCDirac/ILCDIRAC
  except:
    - /.*-pre[0-9]*/
  dependencies:
    - compiledoc
  variables:
    EOS_PATH: "/eos/project/l/lcd-web/www/doc/ilcdiracdoc/"
    CI_OUTPUT_DIR: "ilcdiracdoc"
  script:
    - deploy-eos
  before_script: []
  after_script: []
  retry: 2


docDev:
  stage: manualdeploy
  tags:
    - docker
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  when: manual
  dependencies:
    - compiledoc
    - unittest:SL6
  variables:
    EOS_PATH: "/eos/project/l/lcd-web/www/doc/ilcdiracdocDev/"
    CI_OUTPUT_DIR: "ilcdiracdoc"
  script:
    - mv installation/ILCDIRAC/htmlcov ilcdiracdoc/
    - deploy-eos
  before_script: []
  after_script: []
  retry: 2


docProd:
  stage: manualdeploy
  tags:
    - docker
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  only:
    - branches@CLICdp/iLCDirac/ILCDIRAC
  when: manual
  dependencies:
    - compiledoc
    - unittest:SL6
  variables:
    EOS_PATH: "/eos/project/l/lcd-web/www/doc/ilcdiracdoc/"
    CI_OUTPUT_DIR: "ilcdiracdoc"
  script:
    - mv installation/ILCDIRAC/htmlcov ilcdiracdoc/
    - deploy-eos
  before_script: []
  after_script: []
  retry: 2



deploytag:
  stage: deploy
  tags:
    - docker
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  only:
    - tags@CLICdp/iLCDirac/ILCDIRAC
  dependencies:
    - maketarballs
    - makeILCConfig
  variables:
    EOS_PATH: "/eos/project/l/lcd-web/www/ILCDIRACTars/"
    CI_OUTPUT_DIR: "ILCDIRACTars"
  script:
    - deploy-eos
  before_script: []
  after_script: []
  retry: 2

deployToCVMFS:
  stage: deployToCVMFS
  tags:
    - cvmfs
  only:
    - tags@CLICdp/iLCDirac/ILCDIRAC
  except:
    - /.*-pre[0-9]*/
  dependencies: []
  script:
    - sudo -u cvclicdp -i scripts/installILCDIRAC.sh $CI_COMMIT_TAG $CERT_PASSPHRASE
  before_script: []
  after_script: []
