before_script:
    #pre-installation script
    - cd ..
    - shopt -s extglob
    - rm -rf !(ILCDIRAC)
    - rm -rf .installCache
    - mv ILCDIRAC ILCDIRAC_commit
    - wget -O dirac-install -np  https://raw.github.com/DIRACGrid/DIRAC/master/Core/scripts/dirac-install.py  --no-check-certificate
    - chmod +x dirac-install
    - ./dirac-install -V ILCDIRAC -r v26r0p9 -g 2017-01-27
    - rm -rf DIRAC
    - mkdir DIRAC
    - cd DIRAC
    - git clone https://github.com/DIRACGrid/DIRAC.git .
    - git checkout origin/rel-v6r15
    - cd ..
    - rm -rf ILCDIRAC
    - mv ILCDIRAC_commit ILCDIRAC
    - source bashrc
    - dirac-deploy-scripts
    - unset REQUESTS_CA_BUNDLE
    - pip install --upgrade pip
    - pip install --upgrade setuptools || echo "done"
    - echo "done with setuptools"
    - pip install --upgrade pylint mock MySQL-python pytest-cov pytest-randomly #coverage Check if we need coverage
    - cd ILCDIRAC
    - export HOME=/root/


stages:
    - test

pylint6:
  stage: test
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

unittest6:
  stage: test
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-unittests.sh

cvmfstests6:
  stage: test
  tags:
    - docker
  image: ilcdirac/slc6-extra
  script:
    - source ../bashrc
    - dirac-proxy-init -x <<< $CERT_PASSPHRASE
    - dirac-configure -S ILC-Production -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - echo "mysql:x:0:0:MySQL Server:/var/lib/mysql:/bin/bash" >> /etc/passwd
    - .gitlab-ci.d/run-cvmfstests.sh

cvmfstests7:
  stage: test
  tags:
    - docker
  image: ilcdirac/cc7-extra
  script:
    - source ../bashrc
    - dirac-proxy-init -x <<< $CERT_PASSPHRASE
    - dirac-configure -S ILC-Production -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - echo "mysql:x:0:0:MySQL Server:/var/lib/mysql:/bin/bash" >> /etc/passwd
    - .gitlab-ci.d/run-cvmfstests.sh

pylint7:
  stage: test
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

unittest7:
  stage: test
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-unittests.sh

setests6:
  stage: test
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - dirac-proxy-init -x <<< $CERT_PASSPHRASE
    - dirac-configure -S ILC-Production -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - dirac-proxy-init <<< $CERT_PASSPHRASE
    - .gitlab-ci.d/run-setests.sh


setests7:
  stage: test
  tags:
    - docker
  image: ilcdirac/cc7-extra
  script:
    - source ../bashrc
    - dirac-proxy-init -x <<< $CERT_PASSPHRASE
    - dirac-configure -S ILC-Production -C dips://voilcdirac012.cern.ch:9135/Configuration/Server --SkipCAChecks
    - dirac-proxy-init <<< $CERT_PASSPHRASE
    - .gitlab-ci.d/run-setests.sh
