stages:
    - setUp
    - pylinttests
    - nose56
    - nose7AndCVMFS

.setUpJobTemplate: &setUpScript  # Hidden job, used to define the setupscript
  stage: setUp
  tags:
    - docker
  script:
    #pre-installation script
    - cd ..
    - shopt -s extglob
    - rm -rf !(ILCDIRAC)
    - rm -rf .installCache
    - mv ILCDIRAC ILCDIRAC_commit
    - wget -O dirac-install -np  https://raw.github.com/DIRACGrid/DIRAC/master/Core/scripts/dirac-install.py  --no-check-certificate
    - chmod +x dirac-install
    - ./dirac-install -V ILCDIRAC -r v25r0p0
    - rm -rf DIRAC
    - mkdir DIRAC
    - cd DIRAC
    - git clone https://github.com/DIRACGrid/DIRAC.git .
    - git checkout origin/rel-v6r14
    - cd ..
    - rm -rf ILCDIRAC
    - mv ILCDIRAC_commit ILCDIRAC
    - source bashrc
    - dirac-deploy-scripts
    - pip install --upgrade pip pylint nose mock coverage MySQL-python pytest
    - cd ILCDIRAC
    - export HOME=/root/

setUpJob1:
  image: ilcdirac/slc5-base
  <<: *setUpScript

setUpJob2:
  image: ilcdirac/slc6-base
  <<: *setUpScript

setUpJob3:
  image: ilcdirac/cc7-base
  <<: *setUpScript

setUpJob4:
  image: ilcdirac/slc6-extra
  <<: *setUpScript


pylint5:
  stage: pylinttests
  tags:
    - docker
  image: ilcdirac/slc5-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

nosetest5:
  stage: nose56
  tags:
    - docker
  image: ilcdirac/slc5-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-nosetests.sh

pylint6:
  stage: pylinttests
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

nosetest6:
  stage: nose56
  tags:
    - docker
  image: ilcdirac/slc6-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-nosetests.sh

cvmfstests6:
  stage: nose7AndCVMFS
  tags:
    - docker
  image: ilcdirac/slc6-extra
  script:
    - source ../bashrc
    - dirac-proxy-init -x <<< $CERT_PASSPHRASE
    - dirac-configure -S ILC-Production -C dips://voilcdirac01.cern.ch:9135/Configuration/Server --SkipCAChecks
    - echo "mysql:x:0:0:MySQL Server:/var/lib/mysql:/bin/bash" >> /etc/passwd
    - .gitlab-ci.d/run-cvmfstests.sh

pylint7:
  stage: pylinttests
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-pylint.sh

nosetest7:
  stage: nose7AndCVMFS
  tags:
    - docker
  image: ilcdirac/cc7-base
  script:
    - source ../bashrc
    - .gitlab-ci.d/run-nosetests.sh